import { detectConflicts, detectMissingFields } from "@/src/lib/ai/detection";
import type {
  AiSuggestion,
  ChatMessage,
  DemoSeedBundle,
  EvidenceUnit,
  Lab,
  Protocol,
  ProtocolSnapshot,
  ProtocolStep,
  ProtocolVersion,
  SourceArtifact,
  SourceExcerpt,
  SourceRef,
} from "@/src/types";

export const DEMO_LAB_ID = "lab-neural-systems";
export const DEMO_PROTOCOL_ID = "protocol-western-blot-transfer";
export const USER_CONFIRMED_SOURCE_ID = "source-user-confirmed";
export const DEMO_NOW = "2026-07-23T09:00:00.000Z";

export const demoLab: Lab = {
  id: DEMO_LAB_ID,
  name: "Neural Systems Lab",
  shortName: "NSL",
  field: "신경과학 및 분자생물학",
  description:
    "LabTrace 시연을 위해 만든 가상 연구실입니다. 모든 인물과 자료는 가상입니다.",
  isDemo: true,
  createdAt: "2026-07-20T09:00:00.000Z",
  updatedAt: DEMO_NOW,
};

export const demoProtocol: Protocol = {
  id: DEMO_PROTOCOL_ID,
  labId: DEMO_LAB_ID,
  title: "Western blot membrane transfer 및 antibody incubation",
  objective:
    "서로 다른 인수인계 자료의 충돌과 누락을 검토 가능한 표준 초안으로 통합합니다. 실제 실험 수행 지침이 아닙니다.",
  category: "experiment",
  status: "draft",
  currentVersion: 1,
  tags: ["Western blot", "transfer", "antibody", "demo"],
  createdBy: "LabTrace Demo",
  createdAt: "2026-07-23T08:30:00.000Z",
  updatedAt: DEMO_NOW,
};

export const demoSources: SourceArtifact[] = [
  {
    id: "source-audio-handover",
    protocolId: DEMO_PROTOCOL_ID,
    type: "audio",
    fileName: "seoyun_transfer_handover.m4a",
    displayName: "선배 연구자 음성 인수인계",
    mimeType: "audio/mp4",
    size: 1_284_000,
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    reliability: "current",
    notes: "Demo Mode에서는 사전 전사본을 사용합니다.",
    localBlobKey: "demo-audio-handover",
    extractedText:
      "Transfer는 보통 100볼트에서 60분 진행하고, 끝나면 membrane이 마르지 않게 바로 blocking으로 넘어갑니다. Blocking은 한 시간 정도 했습니다. 밴드가 약할 때는 antibody 농도부터 올리지 말고 transfer가 제대로 됐는지 먼저 확인하세요. PVDF를 사용하는 경우에는 사전 처리가 필요한데, 정확한 시간은 다시 확인해 주세요.",
    processingStatus: "ready",
    createdAt: "2026-07-23T08:31:00.000Z",
  },
  {
    id: "source-handwritten-note",
    protocolId: DEMO_PROTOCOL_ID,
    type: "image",
    fileName: "minjae_transfer_note.png",
    displayName: "손글씨 Transfer 메모",
    mimeType: "image/png",
    size: 218_400,
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
    reliability: "legacy",
    notes: "물음표가 있는 OCR 결과는 불확실성을 유지합니다.",
    localBlobKey: "demo-handwritten-note",
    extractedText:
      "Transfer 90 V / 90 min\nTBST wash 3 × 5 min\nPrimary 1:2000?\nmembrane 절대 말리지 않기",
    processingStatus: "ready",
    createdAt: "2026-07-23T08:32:00.000Z",
  },
  {
    id: "source-reference-pdf",
    protocolId: DEMO_PROTOCOL_ID,
    type: "pdf",
    fileName: "nsl_western_blot_reference_2024.pdf",
    displayName: "기존 Western blot 참고 프로토콜",
    mimeType: "application/pdf",
    size: 346_200,
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    reliability: "reference",
    notes: "2페이지 참고 PDF. 현재 공식 지침으로 자동 확정하지 않습니다.",
    localBlobKey: "demo-reference-pdf",
    extractedText:
      "[1쪽] Transfer 100 V, 60 min. Blocking 5% milk, 30 min.\n[2쪽] Primary antibody 1:1000, overnight at 4°C.",
    processingStatus: "ready",
    createdAt: "2026-07-23T08:33:00.000Z",
  },
  {
    id: "source-current-note",
    protocolId: DEMO_PROTOCOL_ID,
    type: "text",
    fileName: "subin_current_notes.txt",
    displayName: "최신 직접 입력 메모",
    mimeType: "text/plain",
    size: 324,
    author: "이수빈 연구원",
    sourceDate: "2026-07-22",
    reliability: "current",
    notes: "현재 사용 중인 메모",
    extractedText:
      "Phospho-target 실험에서는 milk 대신 BSA를 사용한다. Membrane을 한 번이라도 말리면 background 문제가 생길 수 있으므로 주의한다. Antibody dilution은 target별로 다르므로 공통값으로 확정하지 않는다.",
    processingStatus: "ready",
    createdAt: "2026-07-23T08:34:00.000Z",
  },
  {
    id: "source-troubleshooting",
    protocolId: DEMO_PROTOCOL_ID,
    type: "markdown",
    fileName: "hyunwoo_failures_and_troubleshooting.md",
    displayName: "실패 경험 및 troubleshooting",
    mimeType: "text/markdown",
    size: 498,
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
    reliability: "current",
    notes: "실패 경험을 공식 절차와 분리해 사용합니다.",
    extractedText:
      "- 밴드가 전체적으로 약할 때 transfer 여부부터 확인\n- background가 높으면 washing 조건 및 blocking reagent 확인\n- 예상 위치가 아닌 밴드는 antibody specificity와 sample preparation 확인\n- target마다 조건이 달라 한 가지 dilution을 공통 규칙으로 쓰지 않음",
    processingStatus: "ready",
    createdAt: "2026-07-23T08:35:00.000Z",
  },
];

export const demoExcerpts: SourceExcerpt[] = [
  {
    id: "excerpt-audio-transfer",
    sourceArtifactId: "source-audio-handover",
    excerptText: "Transfer는 보통 100볼트에서 60분 진행하고",
    timestampStart: 0,
    timestampEnd: 5.2,
    confidence: 0.98,
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
  },
  {
    id: "excerpt-audio-blocking",
    sourceArtifactId: "source-audio-handover",
    excerptText:
      "membrane이 마르지 않게 바로 blocking으로 넘어갑니다. Blocking은 한 시간 정도 했습니다.",
    timestampStart: 5.2,
    timestampEnd: 12.8,
    confidence: 0.96,
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
  },
  {
    id: "excerpt-audio-tip",
    sourceArtifactId: "source-audio-handover",
    excerptText:
      "밴드가 약할 때는 antibody 농도부터 올리지 말고 transfer가 제대로 됐는지 먼저 확인하세요.",
    timestampStart: 12.8,
    timestampEnd: 20.1,
    confidence: 0.97,
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
  },
  {
    id: "excerpt-audio-pvdf",
    sourceArtifactId: "source-audio-handover",
    excerptText:
      "PVDF를 사용하는 경우에는 사전 처리가 필요한데, 정확한 시간은 다시 확인해 주세요.",
    timestampStart: 20.1,
    timestampEnd: 27.5,
    confidence: 0.92,
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
  },
  {
    id: "excerpt-image-all",
    sourceArtifactId: "source-handwritten-note",
    excerptText:
      "Transfer 90 V / 90 min · TBST wash 3 × 5 min · Primary 1:2000? · membrane 절대 말리지 않기",
    boundingDescription: "메모 전체, 네 줄의 파란색 손글씨",
    confidence: 0.73,
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
  },
  {
    id: "excerpt-pdf-transfer",
    sourceArtifactId: "source-reference-pdf",
    excerptText: "Transfer 100 V, 60 min. Blocking 5% milk, 30 min.",
    pageNumber: 1,
    confidence: 0.99,
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
  },
  {
    id: "excerpt-pdf-primary",
    sourceArtifactId: "source-reference-pdf",
    excerptText: "Primary antibody 1:1000, overnight at 4°C.",
    pageNumber: 2,
    confidence: 0.99,
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
  },
  {
    id: "excerpt-current-note",
    sourceArtifactId: "source-current-note",
    excerptText:
      "Phospho-target 실험에서는 milk 대신 BSA를 사용한다. Membrane을 한 번이라도 말리면 background 문제가 생길 수 있으므로 주의한다. Antibody dilution은 target별로 다르므로 공통값으로 확정하지 않는다.",
    confidence: 0.99,
    author: "이수빈 연구원",
    sourceDate: "2026-07-22",
  },
  {
    id: "excerpt-troubleshooting",
    sourceArtifactId: "source-troubleshooting",
    excerptText:
      "밴드가 전체적으로 약할 때 transfer 여부부터 확인. background가 높으면 washing 조건 및 blocking reagent 확인. 예상 위치가 아닌 밴드는 antibody specificity와 sample preparation 확인.",
    confidence: 0.99,
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
  },
  {
    id: "excerpt-target-dilution",
    sourceArtifactId: "source-troubleshooting",
    excerptText:
      "target마다 조건이 달라 한 가지 dilution을 공통 규칙으로 쓰지 않음",
    confidence: 0.99,
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
  },
];

export const demoEvidence: EvidenceUnit[] = [
  {
    id: "evidence-audio-transfer",
    sourceArtifactId: "source-audio-handover",
    sourceExcerptId: "excerpt-audio-transfer",
    category: "parameter",
    stepCandidate: "transfer",
    statement: "Transfer는 100 V에서 60분 진행",
    parameterName: "transfer_conditions",
    value: "100 V / 60 min",
    normalizedValue: "100 V / 60 min",
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    timestamp: 0,
    timestampEnd: 5.2,
    quote: "Transfer는 보통 100볼트에서 60분 진행하고",
    confidence: 0.98,
  },
  {
    id: "evidence-audio-blocking-duration",
    sourceArtifactId: "source-audio-handover",
    sourceExcerptId: "excerpt-audio-blocking",
    category: "parameter",
    stepCandidate: "blocking",
    statement: "Blocking은 한 시간 정도 수행",
    parameterName: "blocking_duration",
    value: "60",
    unit: "min",
    normalizedValue: 60,
    normalizedUnit: "min",
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    timestamp: 8.1,
    timestampEnd: 12.8,
    quote: "Blocking은 한 시간 정도 했습니다.",
    confidence: 0.94,
  },
  {
    id: "evidence-audio-dry-warning",
    sourceArtifactId: "source-audio-handover",
    sourceExcerptId: "excerpt-audio-blocking",
    category: "warning",
    stepCandidate: "blocking",
    statement: "Transfer 직후 membrane이 마르지 않게 blocking으로 이동",
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    timestamp: 5.2,
    timestampEnd: 9.1,
    quote: "membrane이 마르지 않게 바로 blocking으로 넘어갑니다.",
    confidence: 0.97,
  },
  {
    id: "evidence-audio-weak-band-tip",
    sourceArtifactId: "source-audio-handover",
    sourceExcerptId: "excerpt-audio-tip",
    category: "implicit_tip",
    stepCandidate: "troubleshooting",
    statement:
      "밴드가 약하면 antibody 농도보다 transfer 상태를 먼저 확인",
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    timestamp: 12.8,
    timestampEnd: 20.1,
    quote:
      "밴드가 약할 때는 antibody 농도부터 올리지 말고 transfer가 제대로 됐는지 먼저 확인하세요.",
    confidence: 0.97,
  },
  {
    id: "evidence-audio-pvdf",
    sourceArtifactId: "source-audio-handover",
    sourceExcerptId: "excerpt-audio-pvdf",
    category: "step",
    stepCandidate: "membrane-preparation",
    statement: "PVDF 사용 시 사전 처리가 필요하나 정확한 시간은 미확인",
    parameterName: "pvdf_pretreatment_conditions",
    author: "박서윤 연구원",
    sourceDate: "2026-07-20",
    timestamp: 20.1,
    timestampEnd: 27.5,
    quote:
      "PVDF를 사용하는 경우에는 사전 처리가 필요한데, 정확한 시간은 다시 확인해 주세요.",
    confidence: 0.74,
    ambiguity: "구체적인 처리 용액과 시간이 확인되지 않음",
  },
  {
    id: "evidence-image-transfer",
    sourceArtifactId: "source-handwritten-note",
    sourceExcerptId: "excerpt-image-all",
    category: "parameter",
    stepCandidate: "transfer",
    statement: "Transfer 90 V / 90 min",
    parameterName: "transfer_conditions",
    value: "90 V / 90 min",
    normalizedValue: "90 V / 90 min",
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
    quote: "Transfer 90 V / 90 min",
    confidence: 0.81,
    ambiguity: "오래된 손글씨 메모",
  },
  {
    id: "evidence-image-wash",
    sourceArtifactId: "source-handwritten-note",
    sourceExcerptId: "excerpt-image-all",
    category: "parameter",
    stepCandidate: "wash",
    statement: "TBST wash를 5분씩 3회",
    parameterName: "tbst_wash",
    value: "3 × 5",
    unit: "min",
    normalizedValue: "3 × 5",
    normalizedUnit: "min",
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
    quote: "TBST wash 3 × 5 min",
    confidence: 0.86,
  },
  {
    id: "evidence-image-primary",
    sourceArtifactId: "source-handwritten-note",
    sourceExcerptId: "excerpt-image-all",
    category: "parameter",
    stepCandidate: "primary-incubation",
    statement: "Primary dilution 1:2000로 보이나 물음표가 있음",
    parameterName: "primary_antibody_dilution",
    value: "1:2000?",
    normalizedValue: "1:2000?",
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
    quote: "Primary 1:2000?",
    confidence: 0.58,
    ambiguity: "원문에 물음표가 있어 확정 불가",
  },
  {
    id: "evidence-image-dry-warning",
    sourceArtifactId: "source-handwritten-note",
    sourceExcerptId: "excerpt-image-all",
    category: "warning",
    stepCandidate: "transfer",
    statement: "Membrane을 말리지 않음",
    author: "김민재 연구원",
    sourceDate: "2025-11-03",
    quote: "membrane 절대 말리지 않기",
    confidence: 0.91,
  },
  {
    id: "evidence-pdf-transfer",
    sourceArtifactId: "source-reference-pdf",
    sourceExcerptId: "excerpt-pdf-transfer",
    category: "parameter",
    stepCandidate: "transfer",
    statement: "Transfer 100 V, 60 min",
    parameterName: "transfer_conditions",
    value: "100 V / 60 min",
    normalizedValue: "100 V / 60 min",
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    pageNumber: 1,
    quote: "Transfer 100 V, 60 min",
    confidence: 0.99,
  },
  {
    id: "evidence-pdf-blocking-duration",
    sourceArtifactId: "source-reference-pdf",
    sourceExcerptId: "excerpt-pdf-transfer",
    category: "parameter",
    stepCandidate: "blocking",
    statement: "Blocking 30 min",
    parameterName: "blocking_duration",
    value: "30",
    unit: "min",
    normalizedValue: 30,
    normalizedUnit: "min",
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    pageNumber: 1,
    quote: "Blocking 5% milk, 30 min",
    confidence: 0.99,
  },
  {
    id: "evidence-pdf-blocking-reagent",
    sourceArtifactId: "source-reference-pdf",
    sourceExcerptId: "excerpt-pdf-transfer",
    category: "material",
    stepCandidate: "blocking",
    statement: "Blocking reagent로 5% milk 사용",
    parameterName: "blocking_reagent",
    value: "5% milk",
    normalizedValue: "5% milk",
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    pageNumber: 1,
    quote: "Blocking 5% milk, 30 min",
    confidence: 0.99,
  },
  {
    id: "evidence-pdf-primary-dilution",
    sourceArtifactId: "source-reference-pdf",
    sourceExcerptId: "excerpt-pdf-primary",
    category: "parameter",
    stepCandidate: "primary-incubation",
    statement: "Primary antibody 1:1000",
    parameterName: "primary_antibody_dilution",
    value: "1:1000",
    normalizedValue: "1:1000",
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    pageNumber: 2,
    quote: "Primary antibody 1:1000, overnight at 4°C",
    confidence: 0.99,
  },
  {
    id: "evidence-pdf-primary-incubation",
    sourceArtifactId: "source-reference-pdf",
    sourceExcerptId: "excerpt-pdf-primary",
    category: "parameter",
    stepCandidate: "primary-incubation",
    statement: "Primary antibody incubation은 4°C overnight",
    parameterName: "primary_incubation",
    value: "overnight",
    unit: "4°C",
    normalizedValue: "overnight",
    normalizedUnit: "4°C",
    author: "Neural Systems Lab 관리자",
    sourceDate: "2024-09-12",
    pageNumber: 2,
    quote: "overnight at 4°C",
    confidence: 0.99,
  },
  {
    id: "evidence-note-bsa",
    sourceArtifactId: "source-current-note",
    sourceExcerptId: "excerpt-current-note",
    category: "material",
    stepCandidate: "blocking",
    statement: "Phospho-target 실험에서는 milk 대신 BSA 사용",
    parameterName: "blocking_reagent",
    value: "BSA (phospho-target)",
    normalizedValue: "BSA (phospho-target)",
    author: "이수빈 연구원",
    sourceDate: "2026-07-22",
    quote: "Phospho-target 실험에서는 milk 대신 BSA를 사용한다.",
    confidence: 0.99,
    ambiguity: "현재 실험의 phospho-target 여부가 확인되지 않음",
  },
  {
    id: "evidence-note-dry-warning",
    sourceArtifactId: "source-current-note",
    sourceExcerptId: "excerpt-current-note",
    category: "warning",
    stepCandidate: "transfer",
    statement: "Membrane 건조 시 background 문제가 생길 수 있음",
    author: "이수빈 연구원",
    sourceDate: "2026-07-22",
    quote:
      "Membrane을 한 번이라도 말리면 background 문제가 생길 수 있으므로 주의한다.",
    confidence: 0.99,
  },
  {
    id: "evidence-note-dilution-variable",
    sourceArtifactId: "source-current-note",
    sourceExcerptId: "excerpt-current-note",
    category: "warning",
    stepCandidate: "primary-incubation",
    statement: "Antibody dilution은 target별로 달라 공통값 확정 불가",
    parameterName: "primary_antibody_dilution",
    value: "target별 상이",
    normalizedValue: "target별 상이",
    author: "이수빈 연구원",
    sourceDate: "2026-07-22",
    quote:
      "Antibody dilution은 target별로 다르므로 공통값으로 확정하지 않는다.",
    confidence: 0.99,
  },
  {
    id: "evidence-trouble-weak",
    sourceArtifactId: "source-troubleshooting",
    sourceExcerptId: "excerpt-troubleshooting",
    category: "troubleshooting",
    stepCandidate: "troubleshooting",
    statement: "밴드가 전체적으로 약하면 transfer 여부부터 확인",
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
    quote: "밴드가 전체적으로 약할 때 transfer 여부부터 확인",
    confidence: 0.99,
  },
  {
    id: "evidence-trouble-background",
    sourceArtifactId: "source-troubleshooting",
    sourceExcerptId: "excerpt-troubleshooting",
    category: "troubleshooting",
    stepCandidate: "troubleshooting",
    statement: "Background가 높으면 washing 조건과 blocking reagent 확인",
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
    quote: "background가 높으면 washing 조건 및 blocking reagent 확인",
    confidence: 0.99,
  },
  {
    id: "evidence-trouble-position",
    sourceArtifactId: "source-troubleshooting",
    sourceExcerptId: "excerpt-troubleshooting",
    category: "troubleshooting",
    stepCandidate: "troubleshooting",
    statement:
      "예상 위치가 아닌 밴드는 antibody specificity와 sample preparation 확인",
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
    quote:
      "예상 위치가 아닌 밴드는 antibody specificity와 sample preparation 확인",
    confidence: 0.99,
  },
  {
    id: "evidence-trouble-dilution-variable",
    sourceArtifactId: "source-troubleshooting",
    sourceExcerptId: "excerpt-target-dilution",
    category: "warning",
    stepCandidate: "primary-incubation",
    statement: "한 가지 dilution을 공통 규칙으로 사용하지 않음",
    parameterName: "primary_antibody_dilution",
    value: "target별 상이",
    normalizedValue: "target별 상이",
    author: "최현우 연구원",
    sourceDate: "2026-06-18",
    quote:
      "target마다 조건이 달라 한 가지 dilution을 공통 규칙으로 쓰지 않음",
    confidence: 0.99,
  },
];

const evidenceMap = new Map(demoEvidence.map((item) => [item.id, item]));
const sourceMap = new Map(demoSources.map((item) => [item.id, item]));

export function demoRef(evidenceId: string): SourceRef {
  const evidence = evidenceMap.get(evidenceId);
  if (!evidence) throw new Error(`Unknown demo evidence: ${evidenceId}`);
  return {
    artifactId: evidence.sourceArtifactId,
    excerptId: evidence.sourceExcerptId,
    sourceLabel:
      sourceMap.get(evidence.sourceArtifactId)?.displayName ??
      evidence.sourceArtifactId,
    author: evidence.author,
    pageNumber: evidence.pageNumber,
    timestampStart: evidence.timestamp,
    timestampEnd: evidence.timestampEnd,
    quote: evidence.quote,
    confidence: evidence.confidence,
  };
}

export const demoConflicts = detectConflicts(demoEvidence, demoSources);
export const demoMissingFields = detectMissingFields(demoEvidence);

const demoSteps: ProtocolStep[] = [
  {
    id: "step-membrane",
    order: 1,
    title: "Membrane 준비",
    action:
      "PVDF를 사용하는 경우 사전 처리가 필요하다는 언급만 확인됨. 사용할 membrane 종류와 구체 조건은 연구자 확인 필요.",
    materials: ["Membrane (종류 미확인)"],
    equipment: [],
    parameters: [],
    duration: "자료에서 확인되지 않음",
    checkpoints: ["PVDF 사용 여부와 사전 처리 조건 확인"],
    implicitTips: [],
    commonMistakes: ["불확실한 사전 처리 조건을 임의로 적용하지 않기"],
    troubleshooting: [],
    successCriteria: ["자료에서 확인되지 않음"],
    sourceRefs: [demoRef("evidence-audio-pvdf")],
    confidence: 0.74,
    unresolved: true,
  },
  {
    id: "step-transfer",
    order: 2,
    title: "Membrane transfer",
    action:
      "Transfer를 진행하되 전압·시간 조합에 미해결 충돌이 있으므로 실행 전 조건을 확정해야 함.",
    materials: ["Membrane (종류 미확인)"],
    equipment: ["Transfer 장비 (모델 미확인)"],
    parameters: [
      {
        name: "Transfer 조건",
        value: "100 V / 60 min 또는 90 V / 90 min (미해결)",
        unit: "",
        sourceRefs: [
          demoRef("evidence-audio-transfer"),
          demoRef("evidence-image-transfer"),
          demoRef("evidence-pdf-transfer"),
        ],
      },
    ],
    duration: "60 min 또는 90 min (미해결)",
    checkpoints: ["조건과 장비 모델을 연구자에게 확인"],
    implicitTips: ["Transfer 후 membrane을 말리지 않고 바로 다음 단계로 이동"],
    commonMistakes: ["Membrane을 건조시키는 것"],
    troubleshooting: [
      "밴드가 전체적으로 약하면 antibody 농도를 바꾸기 전에 transfer 여부 확인",
    ],
    successCriteria: ["자료에서 확인되지 않음"],
    sourceRefs: [
      demoRef("evidence-audio-transfer"),
      demoRef("evidence-image-transfer"),
      demoRef("evidence-pdf-transfer"),
      demoRef("evidence-note-dry-warning"),
    ],
    confidence: 0.86,
    unresolved: true,
  },
  {
    id: "step-blocking",
    order: 3,
    title: "Blocking",
    action:
      "Membrane이 마르지 않게 blocking으로 이동. 시간과 reagent는 충돌 검토 후 확정.",
    materials: ["5% milk 또는 BSA (미해결)"],
    equipment: [],
    parameters: [
      {
        name: "Blocking 시간",
        value: "30 min 또는 60 min (미해결)",
        unit: "",
        sourceRefs: [
          demoRef("evidence-audio-blocking-duration"),
          demoRef("evidence-pdf-blocking-duration"),
        ],
      },
      {
        name: "Blocking reagent",
        value: "5% milk 또는 phospho-target용 BSA (미해결)",
        unit: "",
        sourceRefs: [
          demoRef("evidence-pdf-blocking-reagent"),
          demoRef("evidence-note-bsa"),
        ],
      },
    ],
    duration: "30 min 또는 60 min (미해결)",
    checkpoints: ["현재 target의 phospho-target 여부 확인"],
    implicitTips: ["Membrane이 마르지 않게 바로 blocking으로 이동"],
    commonMistakes: ["Target 맥락 확인 없이 reagent를 공통 적용"],
    troubleshooting: [
      "Background가 높으면 washing 조건 및 blocking reagent 확인",
    ],
    successCriteria: ["자료에서 확인되지 않음"],
    sourceRefs: [
      demoRef("evidence-audio-blocking-duration"),
      demoRef("evidence-pdf-blocking-duration"),
      demoRef("evidence-pdf-blocking-reagent"),
      demoRef("evidence-note-bsa"),
    ],
    confidence: 0.87,
    unresolved: true,
  },
  {
    id: "step-primary",
    order: 4,
    title: "Primary antibody incubation",
    action:
      "Primary antibody를 처리하되 제품과 target별 검증값을 확인하고 dilution 충돌을 먼저 해결.",
    materials: ["Primary antibody (제품 미확인)"],
    equipment: ["4°C 보관 환경"],
    parameters: [
      {
        name: "Dilution",
        value: "1:1000 / 1:2000? / target별 상이 (미해결)",
        unit: "",
        sourceRefs: [
          demoRef("evidence-image-primary"),
          demoRef("evidence-pdf-primary-dilution"),
          demoRef("evidence-note-dilution-variable"),
        ],
      },
      {
        name: "Incubation",
        value: "overnight",
        unit: "4°C",
        normalizedValue: "overnight",
        normalizedUnit: "4°C",
        sourceRefs: [demoRef("evidence-pdf-primary-incubation")],
      },
    ],
    duration: "overnight",
    checkpoints: [
      "Target protein과 antibody 제품의 최근 검증 dilution 확인",
    ],
    implicitTips: [],
    commonMistakes: ["한 가지 dilution을 모든 target의 공통 규칙으로 적용"],
    troubleshooting: [
      "예상 위치가 아닌 밴드는 antibody specificity와 sample preparation 확인",
    ],
    successCriteria: ["자료에서 확인되지 않음"],
    sourceRefs: [
      demoRef("evidence-image-primary"),
      demoRef("evidence-pdf-primary-dilution"),
      demoRef("evidence-pdf-primary-incubation"),
      demoRef("evidence-note-dilution-variable"),
    ],
    confidence: 0.82,
    unresolved: true,
  },
  {
    id: "step-wash",
    order: 5,
    title: "TBST wash",
    action: "TBST로 wash.",
    materials: ["TBST"],
    equipment: [],
    parameters: [
      {
        name: "Wash 횟수와 시간",
        value: "3 × 5",
        unit: "min",
        normalizedValue: "3 × 5",
        normalizedUnit: "min",
        sourceRefs: [demoRef("evidence-image-wash")],
      },
    ],
    duration: "5 min씩 3회",
    checkpoints: [],
    implicitTips: [],
    commonMistakes: [],
    troubleshooting: [
      "Background가 높으면 washing 조건 및 blocking reagent 확인",
    ],
    successCriteria: ["자료에서 확인되지 않음"],
    sourceRefs: [
      demoRef("evidence-image-wash"),
      demoRef("evidence-trouble-background"),
    ],
    confidence: 0.86,
    unresolved: false,
  },
];

export const demoProtocolSnapshot: ProtocolSnapshot = {
  experiment: {
    title: demoProtocol.title,
    objective: demoProtocol.objective,
    category: "experiment",
  },
  materials: [
    "Membrane (종류 미확인)",
    "5% milk 또는 BSA (충돌 미해결)",
    "Primary antibody (제품 미확인)",
    "TBST",
  ],
  equipment: ["Transfer 장비 (모델 미확인)", "4°C 보관 환경"],
  steps: demoSteps,
  conflicts: demoConflicts,
  missingFields: demoMissingFields,
  sources: demoSources,
  overallWarnings: [
    "이 문서는 AI가 입력 자료를 바탕으로 생성한 초안입니다. 실제 실험에 사용하기 전에 담당 연구자와 연구실 책임자의 검토가 필요합니다.",
    "미해결 충돌 4건과 누락 항목 7건을 반드시 확인하세요.",
    "이 데이터의 연구실, 인물, 자료는 모두 해커톤 시연을 위한 가상 정보입니다.",
  ],
};

export const freshDemoProtocolSnapshot: ProtocolSnapshot = {
  experiment: {
    title: demoProtocol.title,
    objective:
      "자료 분석 전입니다. 업로드된 5개 가상 자료에서 evidence를 추출해 초안을 생성하세요.",
    category: "experiment",
  },
  materials: [],
  equipment: [],
  steps: [],
  conflicts: [],
  missingFields: [],
  sources: demoSources.map((source) => ({
    ...source,
    processingStatus: "pending",
  })),
  overallWarnings: [
    "이 데이터의 연구실, 인물, 자료는 모두 해커톤 시연을 위한 가상 정보입니다.",
  ],
};

export const demoSuggestions: AiSuggestion[] = [
  {
    id: "suggestion-transfer-first",
    type: "source_backed",
    title: "약한 밴드 점검 순서",
    content:
      "밴드가 전체적으로 약할 때 antibody 농도를 올리기 전에 transfer 여부부터 확인하세요.",
    sourceRefs: [
      demoRef("evidence-audio-weak-band-tip"),
      demoRef("evidence-trouble-weak"),
    ],
    status: "proposed",
  },
  {
    id: "suggestion-confirm-target",
    type: "clarification_question",
    title: "Target과 antibody 확인",
    content:
      "실험 전 target protein, phospho-target 여부, antibody 제품과 최근 검증 dilution을 담당 연구자에게 확인하세요.",
    sourceRefs: [],
    status: "proposed",
  },
  {
    id: "suggestion-run-log",
    type: "ai_idea",
    title: "실행별 조건 기록",
    content:
      "충돌 해결 후 장비 모델과 실제 적용 조건을 실행별로 기록하는 방안을 검토할 수 있습니다.",
    sourceRefs: [],
    warning: "원본 자료에서 확인되지 않은 AI 아이디어",
    status: "proposed",
  },
];

export const demoWelcomeMessage: ChatMessage = {
  id: "chat-demo-welcome",
  protocolId: DEMO_PROTOCOL_ID,
  role: "assistant",
  content:
    "프로토콜과 다섯 개 원본 자료의 근거 안에서 답변합니다. 자료에 없는 내용은 확인이 필요하다고 표시할게요.",
  citations: [],
  createdAt: DEMO_NOW,
};

export const completedDemoBundle: DemoSeedBundle = {
  lab: demoLab,
  protocols: [demoProtocol],
  versions: [
    {
      id: `${DEMO_PROTOCOL_ID}-v1`,
      protocolId: DEMO_PROTOCOL_ID,
      versionNumber: 1,
      snapshot: demoProtocolSnapshot,
      changeSummary: "5개 인수인계 자료를 통합한 최초 AI 초안",
      changedBy: "LabTrace Demo",
      createdAt: DEMO_NOW,
    },
  ],
  sources: demoSources,
  excerpts: demoExcerpts,
  conflicts: demoConflicts,
  missingFields: demoMissingFields,
  chatMessages: [demoWelcomeMessage],
};

export const freshDemoBundle: DemoSeedBundle = {
  lab: demoLab,
  protocols: [{ ...demoProtocol, currentVersion: 1 }],
  versions: [
    {
      id: `${DEMO_PROTOCOL_ID}-v1`,
      protocolId: DEMO_PROTOCOL_ID,
      versionNumber: 1,
      snapshot: freshDemoProtocolSnapshot,
      changeSummary: "데모 자료 5개를 작업 공간에 불러옴",
      changedBy: "LabTrace Demo",
      createdAt: DEMO_NOW,
    },
  ],
  sources: freshDemoProtocolSnapshot.sources,
  excerpts: [],
  conflicts: [],
  missingFields: [],
  chatMessages: [],
};

export function cloneDemoValue<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function makeDemoVersion(
  snapshot: ProtocolSnapshot,
  versionNumber: number,
  changeSummary: string,
  changedBy = "현재 사용자",
  createdAt = new Date().toISOString(),
): ProtocolVersion {
  return {
    id: `${DEMO_PROTOCOL_ID}-v${versionNumber}-${createdAt}`,
    protocolId: DEMO_PROTOCOL_ID,
    versionNumber,
    snapshot: cloneDemoValue(snapshot),
    changeSummary,
    changedBy,
    createdAt,
  };
}

